// Copyright (c) [2021-2023] [Horizon Robotics][Horizon Bole].
//
// You can use this software according to the terms and conditions of
// the Apache v2.0.
// You may obtain a copy of Apache v2.0. at:
//
//     http: //www.apache.org/licenses/LICENSE-2.0
//
// THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF
// ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
// See Apache v2.0 for more details.

#ifndef SCHEDULEGROUP_ERRORS_H_
#define SCHEDULEGROUP_ERRORS_H_

#include <cstdint>

namespace hobot {
namespace schedulegroup {

constexpr int32_t SCHEDULEGROUP_ERROR_PREFIX = -1110000;

enum ErrorCode : int32_t {
  OK = 0,

  // coroutine scheduler start from -1110100
  COROUTINE_NULL_TASK = -101 + SCHEDULEGROUP_ERROR_PREFIX,
  COROUTINE_NULL_CONTEXT = -102 + SCHEDULEGROUP_ERROR_PREFIX,
  COROUTINE_NOT_RUNNING = -103 + SCHEDULEGROUP_ERROR_PREFIX,
  COROUTINE_NOT_FIND_PRODUCER = -104 + SCHEDULEGROUP_ERROR_PREFIX,
  COROUTINE_NULL_SESSION = -105 + SCHEDULEGROUP_ERROR_PREFIX,
  COROUTINE_SCHEDULER_EXSIT = -106 + SCHEDULEGROUP_ERROR_PREFIX,
  COROUTINE_EXCEPTION_OCCUR = -107 + SCHEDULEGROUP_ERROR_PREFIX,
  COROUTINE_TOO_LARGE_PRIO = -108 + SCHEDULEGROUP_ERROR_PREFIX,
  COROUTINE_INVALID_INDEX = -109 + SCHEDULEGROUP_ERROR_PREFIX,
  COROUTINE_INDEX_STOPPED = -110 + SCHEDULEGROUP_ERROR_PREFIX,
  COROUTINE_TOO_MANY_COROUTINES = -111 + SCHEDULEGROUP_ERROR_PREFIX,
  // deadline scheduler start from -1110200

  // threadpool scheduler start from -1110300
  THREADPOOL_NOT_RUNNING = -301 + SCHEDULEGROUP_ERROR_PREFIX,
  THREADPOOL_NULL_TASK = -302 + SCHEDULEGROUP_ERROR_PREFIX,
  THREADPOOL_INVALID_TASK = -303 + SCHEDULEGROUP_ERROR_PREFIX,
  THREADPOOL_TASK_PRIORITY_TOO_LARGE = -304 + SCHEDULEGROUP_ERROR_PREFIX,

  // time affi scheduler start from -1110400
  TIME_AFFI_SCHEDULER_STOPPED = -401 + SCHEDULEGROUP_ERROR_PREFIX,
  TIME_AFFI_SCHEDULER_UNFIND = -402 + SCHEDULEGROUP_ERROR_PREFIX,

  // timer scheduler start from -1110500
  // Deprecated, reserved for compatibility
  TIMER_INVALID_PRODUCER_NAME = -501 + SCHEDULEGROUP_ERROR_PREFIX,
  TIMER_FAIL_CANCEL_TIMER = -502 + SCHEDULEGROUP_ERROR_PREFIX,
  TIMER_NOT_RUNNING = -503 + SCHEDULEGROUP_ERROR_PREFIX,
  TIMER_UNABLE_ADD_TIMER = -504 + SCHEDULEGROUP_ERROR_PREFIX,
  TIMER_NULL_TASK = -505 + SCHEDULEGROUP_ERROR_PREFIX,
  TIMER_NULL_TIMER_MANAGER = -506 + SCHEDULEGROUP_ERROR_PREFIX,

  // ERROR_CODE_SCHEDULE_GROUP_CREATE start from -1110600
  SCHEDULE_GROUP_NAME_EMPTY = -601 + SCHEDULEGROUP_ERROR_PREFIX,
  SCHEDULE_GROUP_NAME_ALREADY_EXIST = -602 + SCHEDULEGROUP_ERROR_PREFIX,
  SCHEDULE_GROUP_NOT_EXIST = -603 + SCHEDULEGROUP_ERROR_PREFIX,
  SCHEDULE_GROUP_THREAD_SIZE_EXCEEDED = -604 + SCHEDULEGROUP_ERROR_PREFIX,
  SCHEDULE_GROUP_ALREADY_EXIST = -605 + SCHEDULEGROUP_ERROR_PREFIX,
  SCHEDULE_GROUP_CREATE_EXCEPTION = -606 + SCHEDULEGROUP_ERROR_PREFIX,
  SCHEDULE_GROUP_NULL_TASK = -607 + SCHEDULEGROUP_ERROR_PREFIX,
  SCHEDULE_GROUP_FEATURE_UNSUPPORTED = -608 + SCHEDULEGROUP_ERROR_PREFIX,
  SCHEDULE_GROUP_THREAD_INDEX_ERROR = -609 + SCHEDULEGROUP_ERROR_PREFIX,
  SCHEDULE_GROUP_THREAD_NOT_JOINABLE = -610 + SCHEDULEGROUP_ERROR_PREFIX,

  // simple scheduler start from -1110700
  SIMPLE_SCHEDULER_NOT_RUNNING = -701 + SCHEDULEGROUP_ERROR_PREFIX,
  SIMPLE_SCHEDULER_NULL_TASK = -702 + SCHEDULEGROUP_ERROR_PREFIX,
  SIMPLE_SCHEDULER_TASK_THREAD_INDEX_TOO_LARGE =
      -703 + SCHEDULEGROUP_ERROR_PREFIX
};

}  // namespace schedulegroup
}  // namespace hobot

#endif  // SCHEDULEGROUP_ERRORS_H_
