// Copyright (c) [2021-2023] [Horizon Robotics][Horizon Bole].
//
// You can use this software according to the terms and conditions of
// the Apache v2.0.
// You may obtain a copy of Apache v2.0. at:
//
//     http: //www.apache.org/licenses/LICENSE-2.0
//
// THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF
// ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
// See Apache v2.0 for more details.
// This file is automatically generated by CMake, do not modify it manually.

#ifndef SRC_SCHEDULEGROUP_VERSION_H_
#define SRC_SCHEDULEGROUP_VERSION_H_

#define SCHEDULEGROUP_VERSION_MAJOR 1
#define SCHEDULEGROUP_VERSION_MINOR 4
#define SCHEDULEGROUP_VERSION_PATCH 5

#endif  // SRC_SCHEDULEGROUP_VERSION_H_
