// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aph.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_aph_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_aph_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_aph_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_aph_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_aph_2eproto;
namespace aph {
class FusionSlotInfo;
struct FusionSlotInfoDefaultTypeInternal;
extern FusionSlotInfoDefaultTypeInternal _FusionSlotInfo_default_instance_;
class FusionSlotInfo2Location;
struct FusionSlotInfo2LocationDefaultTypeInternal;
extern FusionSlotInfo2LocationDefaultTypeInternal _FusionSlotInfo2Location_default_instance_;
class SlotPoint;
struct SlotPointDefaultTypeInternal;
extern SlotPointDefaultTypeInternal _SlotPoint_default_instance_;
class apa_status;
struct apa_statusDefaultTypeInternal;
extern apa_statusDefaultTypeInternal _apa_status_default_instance_;
class target_slot;
struct target_slotDefaultTypeInternal;
extern target_slotDefaultTypeInternal _target_slot_default_instance_;
}  // namespace aph
PROTOBUF_NAMESPACE_OPEN
template<> ::aph::FusionSlotInfo* Arena::CreateMaybeMessage<::aph::FusionSlotInfo>(Arena*);
template<> ::aph::FusionSlotInfo2Location* Arena::CreateMaybeMessage<::aph::FusionSlotInfo2Location>(Arena*);
template<> ::aph::SlotPoint* Arena::CreateMaybeMessage<::aph::SlotPoint>(Arena*);
template<> ::aph::apa_status* Arena::CreateMaybeMessage<::aph::apa_status>(Arena*);
template<> ::aph::target_slot* Arena::CreateMaybeMessage<::aph::target_slot>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace aph {

enum ApaStatusType : int {
  APA_STATUS_OFF = 0,
  APA_STATUS_STANDBY = 1,
  APA_STATUS_SEARCHING = 2,
  APA_STATUS_EXIT_PARK = 3,
  APA_STATUS_ENABLE = 4,
  APA_STATUS_GUIDANCE = 5,
  APA_STATUS_FINISH = 6,
  APA_STATUS_ERROR = 7,
  APA_STATUS_PARKING = 8,
  APA_STATUS_RESERVED = 9,
  ApaStatusType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ApaStatusType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ApaStatusType_IsValid(int value);
constexpr ApaStatusType ApaStatusType_MIN = APA_STATUS_OFF;
constexpr ApaStatusType ApaStatusType_MAX = APA_STATUS_RESERVED;
constexpr int ApaStatusType_ARRAYSIZE = ApaStatusType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ApaStatusType_descriptor();
template<typename T>
inline const std::string& ApaStatusType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ApaStatusType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ApaStatusType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ApaStatusType_descriptor(), enum_t_value);
}
inline bool ApaStatusType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ApaStatusType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ApaStatusType>(
    ApaStatusType_descriptor(), name, value);
}
// ===================================================================

class apa_status final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aph.apa_status) */ {
 public:
  inline apa_status() : apa_status(nullptr) {}
  ~apa_status() override;
  explicit constexpr apa_status(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  apa_status(const apa_status& from);
  apa_status(apa_status&& from) noexcept
    : apa_status() {
    *this = ::std::move(from);
  }

  inline apa_status& operator=(const apa_status& from) {
    CopyFrom(from);
    return *this;
  }
  inline apa_status& operator=(apa_status&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const apa_status& default_instance() {
    return *internal_default_instance();
  }
  static inline const apa_status* internal_default_instance() {
    return reinterpret_cast<const apa_status*>(
               &_apa_status_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(apa_status& a, apa_status& b) {
    a.Swap(&b);
  }
  inline void Swap(apa_status* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(apa_status* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  apa_status* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<apa_status>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const apa_status& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const apa_status& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(apa_status* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aph.apa_status";
  }
  protected:
  explicit apa_status(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMCurrentApaStatusFieldNumber = 1,
  };
  // optional .aph.ApaStatusType m_current_apa_status = 1;
  bool has_m_current_apa_status() const;
  private:
  bool _internal_has_m_current_apa_status() const;
  public:
  void clear_m_current_apa_status();
  ::aph::ApaStatusType m_current_apa_status() const;
  void set_m_current_apa_status(::aph::ApaStatusType value);
  private:
  ::aph::ApaStatusType _internal_m_current_apa_status() const;
  void _internal_set_m_current_apa_status(::aph::ApaStatusType value);
  public:

  // @@protoc_insertion_point(class_scope:aph.apa_status)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  int m_current_apa_status_;
  friend struct ::TableStruct_aph_2eproto;
};
// -------------------------------------------------------------------

class target_slot final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aph.target_slot) */ {
 public:
  inline target_slot() : target_slot(nullptr) {}
  ~target_slot() override;
  explicit constexpr target_slot(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  target_slot(const target_slot& from);
  target_slot(target_slot&& from) noexcept
    : target_slot() {
    *this = ::std::move(from);
  }

  inline target_slot& operator=(const target_slot& from) {
    CopyFrom(from);
    return *this;
  }
  inline target_slot& operator=(target_slot&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const target_slot& default_instance() {
    return *internal_default_instance();
  }
  static inline const target_slot* internal_default_instance() {
    return reinterpret_cast<const target_slot*>(
               &_target_slot_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(target_slot& a, target_slot& b) {
    a.Swap(&b);
  }
  inline void Swap(target_slot* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(target_slot* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  target_slot* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<target_slot>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const target_slot& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const target_slot& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(target_slot* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aph.target_slot";
  }
  protected:
  explicit target_slot(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMUserSelectSlotLabelIdxFieldNumber = 1,
  };
  // optional int32 m_user_select_slot_label_idx = 1;
  bool has_m_user_select_slot_label_idx() const;
  private:
  bool _internal_has_m_user_select_slot_label_idx() const;
  public:
  void clear_m_user_select_slot_label_idx();
  int32_t m_user_select_slot_label_idx() const;
  void set_m_user_select_slot_label_idx(int32_t value);
  private:
  int32_t _internal_m_user_select_slot_label_idx() const;
  void _internal_set_m_user_select_slot_label_idx(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:aph.target_slot)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  int32_t m_user_select_slot_label_idx_;
  friend struct ::TableStruct_aph_2eproto;
};
// -------------------------------------------------------------------

class FusionSlotInfo2Location final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aph.FusionSlotInfo2Location) */ {
 public:
  inline FusionSlotInfo2Location() : FusionSlotInfo2Location(nullptr) {}
  ~FusionSlotInfo2Location() override;
  explicit constexpr FusionSlotInfo2Location(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FusionSlotInfo2Location(const FusionSlotInfo2Location& from);
  FusionSlotInfo2Location(FusionSlotInfo2Location&& from) noexcept
    : FusionSlotInfo2Location() {
    *this = ::std::move(from);
  }

  inline FusionSlotInfo2Location& operator=(const FusionSlotInfo2Location& from) {
    CopyFrom(from);
    return *this;
  }
  inline FusionSlotInfo2Location& operator=(FusionSlotInfo2Location&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FusionSlotInfo2Location& default_instance() {
    return *internal_default_instance();
  }
  static inline const FusionSlotInfo2Location* internal_default_instance() {
    return reinterpret_cast<const FusionSlotInfo2Location*>(
               &_FusionSlotInfo2Location_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(FusionSlotInfo2Location& a, FusionSlotInfo2Location& b) {
    a.Swap(&b);
  }
  inline void Swap(FusionSlotInfo2Location* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FusionSlotInfo2Location* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FusionSlotInfo2Location* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FusionSlotInfo2Location>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FusionSlotInfo2Location& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const FusionSlotInfo2Location& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FusionSlotInfo2Location* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aph.FusionSlotInfo2Location";
  }
  protected:
  explicit FusionSlotInfo2Location(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFusionSlotInfosFieldNumber = 2,
    kSlotNumFieldNumber = 1,
  };
  // repeated .aph.FusionSlotInfo fusionSlotInfos = 2;
  int fusionslotinfos_size() const;
  private:
  int _internal_fusionslotinfos_size() const;
  public:
  void clear_fusionslotinfos();
  ::aph::FusionSlotInfo* mutable_fusionslotinfos(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aph::FusionSlotInfo >*
      mutable_fusionslotinfos();
  private:
  const ::aph::FusionSlotInfo& _internal_fusionslotinfos(int index) const;
  ::aph::FusionSlotInfo* _internal_add_fusionslotinfos();
  public:
  const ::aph::FusionSlotInfo& fusionslotinfos(int index) const;
  ::aph::FusionSlotInfo* add_fusionslotinfos();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aph::FusionSlotInfo >&
      fusionslotinfos() const;

  // optional int32 slotNum = 1;
  bool has_slotnum() const;
  private:
  bool _internal_has_slotnum() const;
  public:
  void clear_slotnum();
  int32_t slotnum() const;
  void set_slotnum(int32_t value);
  private:
  int32_t _internal_slotnum() const;
  void _internal_set_slotnum(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:aph.FusionSlotInfo2Location)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aph::FusionSlotInfo > fusionslotinfos_;
  int32_t slotnum_;
  friend struct ::TableStruct_aph_2eproto;
};
// -------------------------------------------------------------------

class FusionSlotInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aph.FusionSlotInfo) */ {
 public:
  inline FusionSlotInfo() : FusionSlotInfo(nullptr) {}
  ~FusionSlotInfo() override;
  explicit constexpr FusionSlotInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FusionSlotInfo(const FusionSlotInfo& from);
  FusionSlotInfo(FusionSlotInfo&& from) noexcept
    : FusionSlotInfo() {
    *this = ::std::move(from);
  }

  inline FusionSlotInfo& operator=(const FusionSlotInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline FusionSlotInfo& operator=(FusionSlotInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FusionSlotInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const FusionSlotInfo* internal_default_instance() {
    return reinterpret_cast<const FusionSlotInfo*>(
               &_FusionSlotInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(FusionSlotInfo& a, FusionSlotInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(FusionSlotInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FusionSlotInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FusionSlotInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FusionSlotInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FusionSlotInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const FusionSlotInfo& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FusionSlotInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aph.FusionSlotInfo";
  }
  protected:
  explicit FusionSlotInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPtFieldNumber = 1,
    kSlotTypeFieldNumber = 2,
    kFusionSlotTypeFieldNumber = 3,
    kSlotLabelFieldNumber = 4,
    kDisplayLabelFieldNumber = 5,
    kSlotInnerObTypeFieldNumber = 6,
    kSlotStatusTypeFieldNumber = 7,
  };
  // repeated .aph.SlotPoint pt = 1;
  int pt_size() const;
  private:
  int _internal_pt_size() const;
  public:
  void clear_pt();
  ::aph::SlotPoint* mutable_pt(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aph::SlotPoint >*
      mutable_pt();
  private:
  const ::aph::SlotPoint& _internal_pt(int index) const;
  ::aph::SlotPoint* _internal_add_pt();
  public:
  const ::aph::SlotPoint& pt(int index) const;
  ::aph::SlotPoint* add_pt();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aph::SlotPoint >&
      pt() const;

  // optional int32 slotType = 2;
  bool has_slottype() const;
  private:
  bool _internal_has_slottype() const;
  public:
  void clear_slottype();
  int32_t slottype() const;
  void set_slottype(int32_t value);
  private:
  int32_t _internal_slottype() const;
  void _internal_set_slottype(int32_t value);
  public:

  // optional int32 fusionSlotType = 3;
  bool has_fusionslottype() const;
  private:
  bool _internal_has_fusionslottype() const;
  public:
  void clear_fusionslottype();
  int32_t fusionslottype() const;
  void set_fusionslottype(int32_t value);
  private:
  int32_t _internal_fusionslottype() const;
  void _internal_set_fusionslottype(int32_t value);
  public:

  // optional int32 slotLabel = 4;
  bool has_slotlabel() const;
  private:
  bool _internal_has_slotlabel() const;
  public:
  void clear_slotlabel();
  int32_t slotlabel() const;
  void set_slotlabel(int32_t value);
  private:
  int32_t _internal_slotlabel() const;
  void _internal_set_slotlabel(int32_t value);
  public:

  // optional int32 displayLabel = 5;
  bool has_displaylabel() const;
  private:
  bool _internal_has_displaylabel() const;
  public:
  void clear_displaylabel();
  int32_t displaylabel() const;
  void set_displaylabel(int32_t value);
  private:
  int32_t _internal_displaylabel() const;
  void _internal_set_displaylabel(int32_t value);
  public:

  // optional int32 slotInnerObType = 6;
  bool has_slotinnerobtype() const;
  private:
  bool _internal_has_slotinnerobtype() const;
  public:
  void clear_slotinnerobtype();
  int32_t slotinnerobtype() const;
  void set_slotinnerobtype(int32_t value);
  private:
  int32_t _internal_slotinnerobtype() const;
  void _internal_set_slotinnerobtype(int32_t value);
  public:

  // optional int32 slotStatusType = 7;
  bool has_slotstatustype() const;
  private:
  bool _internal_has_slotstatustype() const;
  public:
  void clear_slotstatustype();
  int32_t slotstatustype() const;
  void set_slotstatustype(int32_t value);
  private:
  int32_t _internal_slotstatustype() const;
  void _internal_set_slotstatustype(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:aph.FusionSlotInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aph::SlotPoint > pt_;
  int32_t slottype_;
  int32_t fusionslottype_;
  int32_t slotlabel_;
  int32_t displaylabel_;
  int32_t slotinnerobtype_;
  int32_t slotstatustype_;
  friend struct ::TableStruct_aph_2eproto;
};
// -------------------------------------------------------------------

class SlotPoint final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aph.SlotPoint) */ {
 public:
  inline SlotPoint() : SlotPoint(nullptr) {}
  ~SlotPoint() override;
  explicit constexpr SlotPoint(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SlotPoint(const SlotPoint& from);
  SlotPoint(SlotPoint&& from) noexcept
    : SlotPoint() {
    *this = ::std::move(from);
  }

  inline SlotPoint& operator=(const SlotPoint& from) {
    CopyFrom(from);
    return *this;
  }
  inline SlotPoint& operator=(SlotPoint&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SlotPoint& default_instance() {
    return *internal_default_instance();
  }
  static inline const SlotPoint* internal_default_instance() {
    return reinterpret_cast<const SlotPoint*>(
               &_SlotPoint_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(SlotPoint& a, SlotPoint& b) {
    a.Swap(&b);
  }
  inline void Swap(SlotPoint* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SlotPoint* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SlotPoint* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SlotPoint>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SlotPoint& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const SlotPoint& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SlotPoint* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aph.SlotPoint";
  }
  protected:
  explicit SlotPoint(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // optional int32 x = 1;
  bool has_x() const;
  private:
  bool _internal_has_x() const;
  public:
  void clear_x();
  int32_t x() const;
  void set_x(int32_t value);
  private:
  int32_t _internal_x() const;
  void _internal_set_x(int32_t value);
  public:

  // optional int32 y = 2;
  bool has_y() const;
  private:
  bool _internal_has_y() const;
  public:
  void clear_y();
  int32_t y() const;
  void set_y(int32_t value);
  private:
  int32_t _internal_y() const;
  void _internal_set_y(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:aph.SlotPoint)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  int32_t x_;
  int32_t y_;
  friend struct ::TableStruct_aph_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// apa_status

// optional .aph.ApaStatusType m_current_apa_status = 1;
inline bool apa_status::_internal_has_m_current_apa_status() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool apa_status::has_m_current_apa_status() const {
  return _internal_has_m_current_apa_status();
}
inline void apa_status::clear_m_current_apa_status() {
  m_current_apa_status_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::aph::ApaStatusType apa_status::_internal_m_current_apa_status() const {
  return static_cast< ::aph::ApaStatusType >(m_current_apa_status_);
}
inline ::aph::ApaStatusType apa_status::m_current_apa_status() const {
  // @@protoc_insertion_point(field_get:aph.apa_status.m_current_apa_status)
  return _internal_m_current_apa_status();
}
inline void apa_status::_internal_set_m_current_apa_status(::aph::ApaStatusType value) {
  _has_bits_[0] |= 0x00000001u;
  m_current_apa_status_ = value;
}
inline void apa_status::set_m_current_apa_status(::aph::ApaStatusType value) {
  _internal_set_m_current_apa_status(value);
  // @@protoc_insertion_point(field_set:aph.apa_status.m_current_apa_status)
}

// -------------------------------------------------------------------

// target_slot

// optional int32 m_user_select_slot_label_idx = 1;
inline bool target_slot::_internal_has_m_user_select_slot_label_idx() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool target_slot::has_m_user_select_slot_label_idx() const {
  return _internal_has_m_user_select_slot_label_idx();
}
inline void target_slot::clear_m_user_select_slot_label_idx() {
  m_user_select_slot_label_idx_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline int32_t target_slot::_internal_m_user_select_slot_label_idx() const {
  return m_user_select_slot_label_idx_;
}
inline int32_t target_slot::m_user_select_slot_label_idx() const {
  // @@protoc_insertion_point(field_get:aph.target_slot.m_user_select_slot_label_idx)
  return _internal_m_user_select_slot_label_idx();
}
inline void target_slot::_internal_set_m_user_select_slot_label_idx(int32_t value) {
  _has_bits_[0] |= 0x00000001u;
  m_user_select_slot_label_idx_ = value;
}
inline void target_slot::set_m_user_select_slot_label_idx(int32_t value) {
  _internal_set_m_user_select_slot_label_idx(value);
  // @@protoc_insertion_point(field_set:aph.target_slot.m_user_select_slot_label_idx)
}

// -------------------------------------------------------------------

// FusionSlotInfo2Location

// optional int32 slotNum = 1;
inline bool FusionSlotInfo2Location::_internal_has_slotnum() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool FusionSlotInfo2Location::has_slotnum() const {
  return _internal_has_slotnum();
}
inline void FusionSlotInfo2Location::clear_slotnum() {
  slotnum_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline int32_t FusionSlotInfo2Location::_internal_slotnum() const {
  return slotnum_;
}
inline int32_t FusionSlotInfo2Location::slotnum() const {
  // @@protoc_insertion_point(field_get:aph.FusionSlotInfo2Location.slotNum)
  return _internal_slotnum();
}
inline void FusionSlotInfo2Location::_internal_set_slotnum(int32_t value) {
  _has_bits_[0] |= 0x00000001u;
  slotnum_ = value;
}
inline void FusionSlotInfo2Location::set_slotnum(int32_t value) {
  _internal_set_slotnum(value);
  // @@protoc_insertion_point(field_set:aph.FusionSlotInfo2Location.slotNum)
}

// repeated .aph.FusionSlotInfo fusionSlotInfos = 2;
inline int FusionSlotInfo2Location::_internal_fusionslotinfos_size() const {
  return fusionslotinfos_.size();
}
inline int FusionSlotInfo2Location::fusionslotinfos_size() const {
  return _internal_fusionslotinfos_size();
}
inline void FusionSlotInfo2Location::clear_fusionslotinfos() {
  fusionslotinfos_.Clear();
}
inline ::aph::FusionSlotInfo* FusionSlotInfo2Location::mutable_fusionslotinfos(int index) {
  // @@protoc_insertion_point(field_mutable:aph.FusionSlotInfo2Location.fusionSlotInfos)
  return fusionslotinfos_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aph::FusionSlotInfo >*
FusionSlotInfo2Location::mutable_fusionslotinfos() {
  // @@protoc_insertion_point(field_mutable_list:aph.FusionSlotInfo2Location.fusionSlotInfos)
  return &fusionslotinfos_;
}
inline const ::aph::FusionSlotInfo& FusionSlotInfo2Location::_internal_fusionslotinfos(int index) const {
  return fusionslotinfos_.Get(index);
}
inline const ::aph::FusionSlotInfo& FusionSlotInfo2Location::fusionslotinfos(int index) const {
  // @@protoc_insertion_point(field_get:aph.FusionSlotInfo2Location.fusionSlotInfos)
  return _internal_fusionslotinfos(index);
}
inline ::aph::FusionSlotInfo* FusionSlotInfo2Location::_internal_add_fusionslotinfos() {
  return fusionslotinfos_.Add();
}
inline ::aph::FusionSlotInfo* FusionSlotInfo2Location::add_fusionslotinfos() {
  ::aph::FusionSlotInfo* _add = _internal_add_fusionslotinfos();
  // @@protoc_insertion_point(field_add:aph.FusionSlotInfo2Location.fusionSlotInfos)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aph::FusionSlotInfo >&
FusionSlotInfo2Location::fusionslotinfos() const {
  // @@protoc_insertion_point(field_list:aph.FusionSlotInfo2Location.fusionSlotInfos)
  return fusionslotinfos_;
}

// -------------------------------------------------------------------

// FusionSlotInfo

// repeated .aph.SlotPoint pt = 1;
inline int FusionSlotInfo::_internal_pt_size() const {
  return pt_.size();
}
inline int FusionSlotInfo::pt_size() const {
  return _internal_pt_size();
}
inline void FusionSlotInfo::clear_pt() {
  pt_.Clear();
}
inline ::aph::SlotPoint* FusionSlotInfo::mutable_pt(int index) {
  // @@protoc_insertion_point(field_mutable:aph.FusionSlotInfo.pt)
  return pt_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aph::SlotPoint >*
FusionSlotInfo::mutable_pt() {
  // @@protoc_insertion_point(field_mutable_list:aph.FusionSlotInfo.pt)
  return &pt_;
}
inline const ::aph::SlotPoint& FusionSlotInfo::_internal_pt(int index) const {
  return pt_.Get(index);
}
inline const ::aph::SlotPoint& FusionSlotInfo::pt(int index) const {
  // @@protoc_insertion_point(field_get:aph.FusionSlotInfo.pt)
  return _internal_pt(index);
}
inline ::aph::SlotPoint* FusionSlotInfo::_internal_add_pt() {
  return pt_.Add();
}
inline ::aph::SlotPoint* FusionSlotInfo::add_pt() {
  ::aph::SlotPoint* _add = _internal_add_pt();
  // @@protoc_insertion_point(field_add:aph.FusionSlotInfo.pt)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aph::SlotPoint >&
FusionSlotInfo::pt() const {
  // @@protoc_insertion_point(field_list:aph.FusionSlotInfo.pt)
  return pt_;
}

// optional int32 slotType = 2;
inline bool FusionSlotInfo::_internal_has_slottype() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool FusionSlotInfo::has_slottype() const {
  return _internal_has_slottype();
}
inline void FusionSlotInfo::clear_slottype() {
  slottype_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline int32_t FusionSlotInfo::_internal_slottype() const {
  return slottype_;
}
inline int32_t FusionSlotInfo::slottype() const {
  // @@protoc_insertion_point(field_get:aph.FusionSlotInfo.slotType)
  return _internal_slottype();
}
inline void FusionSlotInfo::_internal_set_slottype(int32_t value) {
  _has_bits_[0] |= 0x00000001u;
  slottype_ = value;
}
inline void FusionSlotInfo::set_slottype(int32_t value) {
  _internal_set_slottype(value);
  // @@protoc_insertion_point(field_set:aph.FusionSlotInfo.slotType)
}

// optional int32 fusionSlotType = 3;
inline bool FusionSlotInfo::_internal_has_fusionslottype() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool FusionSlotInfo::has_fusionslottype() const {
  return _internal_has_fusionslottype();
}
inline void FusionSlotInfo::clear_fusionslottype() {
  fusionslottype_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline int32_t FusionSlotInfo::_internal_fusionslottype() const {
  return fusionslottype_;
}
inline int32_t FusionSlotInfo::fusionslottype() const {
  // @@protoc_insertion_point(field_get:aph.FusionSlotInfo.fusionSlotType)
  return _internal_fusionslottype();
}
inline void FusionSlotInfo::_internal_set_fusionslottype(int32_t value) {
  _has_bits_[0] |= 0x00000002u;
  fusionslottype_ = value;
}
inline void FusionSlotInfo::set_fusionslottype(int32_t value) {
  _internal_set_fusionslottype(value);
  // @@protoc_insertion_point(field_set:aph.FusionSlotInfo.fusionSlotType)
}

// optional int32 slotLabel = 4;
inline bool FusionSlotInfo::_internal_has_slotlabel() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool FusionSlotInfo::has_slotlabel() const {
  return _internal_has_slotlabel();
}
inline void FusionSlotInfo::clear_slotlabel() {
  slotlabel_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline int32_t FusionSlotInfo::_internal_slotlabel() const {
  return slotlabel_;
}
inline int32_t FusionSlotInfo::slotlabel() const {
  // @@protoc_insertion_point(field_get:aph.FusionSlotInfo.slotLabel)
  return _internal_slotlabel();
}
inline void FusionSlotInfo::_internal_set_slotlabel(int32_t value) {
  _has_bits_[0] |= 0x00000004u;
  slotlabel_ = value;
}
inline void FusionSlotInfo::set_slotlabel(int32_t value) {
  _internal_set_slotlabel(value);
  // @@protoc_insertion_point(field_set:aph.FusionSlotInfo.slotLabel)
}

// optional int32 displayLabel = 5;
inline bool FusionSlotInfo::_internal_has_displaylabel() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool FusionSlotInfo::has_displaylabel() const {
  return _internal_has_displaylabel();
}
inline void FusionSlotInfo::clear_displaylabel() {
  displaylabel_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline int32_t FusionSlotInfo::_internal_displaylabel() const {
  return displaylabel_;
}
inline int32_t FusionSlotInfo::displaylabel() const {
  // @@protoc_insertion_point(field_get:aph.FusionSlotInfo.displayLabel)
  return _internal_displaylabel();
}
inline void FusionSlotInfo::_internal_set_displaylabel(int32_t value) {
  _has_bits_[0] |= 0x00000008u;
  displaylabel_ = value;
}
inline void FusionSlotInfo::set_displaylabel(int32_t value) {
  _internal_set_displaylabel(value);
  // @@protoc_insertion_point(field_set:aph.FusionSlotInfo.displayLabel)
}

// optional int32 slotInnerObType = 6;
inline bool FusionSlotInfo::_internal_has_slotinnerobtype() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool FusionSlotInfo::has_slotinnerobtype() const {
  return _internal_has_slotinnerobtype();
}
inline void FusionSlotInfo::clear_slotinnerobtype() {
  slotinnerobtype_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline int32_t FusionSlotInfo::_internal_slotinnerobtype() const {
  return slotinnerobtype_;
}
inline int32_t FusionSlotInfo::slotinnerobtype() const {
  // @@protoc_insertion_point(field_get:aph.FusionSlotInfo.slotInnerObType)
  return _internal_slotinnerobtype();
}
inline void FusionSlotInfo::_internal_set_slotinnerobtype(int32_t value) {
  _has_bits_[0] |= 0x00000010u;
  slotinnerobtype_ = value;
}
inline void FusionSlotInfo::set_slotinnerobtype(int32_t value) {
  _internal_set_slotinnerobtype(value);
  // @@protoc_insertion_point(field_set:aph.FusionSlotInfo.slotInnerObType)
}

// optional int32 slotStatusType = 7;
inline bool FusionSlotInfo::_internal_has_slotstatustype() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool FusionSlotInfo::has_slotstatustype() const {
  return _internal_has_slotstatustype();
}
inline void FusionSlotInfo::clear_slotstatustype() {
  slotstatustype_ = 0;
  _has_bits_[0] &= ~0x00000020u;
}
inline int32_t FusionSlotInfo::_internal_slotstatustype() const {
  return slotstatustype_;
}
inline int32_t FusionSlotInfo::slotstatustype() const {
  // @@protoc_insertion_point(field_get:aph.FusionSlotInfo.slotStatusType)
  return _internal_slotstatustype();
}
inline void FusionSlotInfo::_internal_set_slotstatustype(int32_t value) {
  _has_bits_[0] |= 0x00000020u;
  slotstatustype_ = value;
}
inline void FusionSlotInfo::set_slotstatustype(int32_t value) {
  _internal_set_slotstatustype(value);
  // @@protoc_insertion_point(field_set:aph.FusionSlotInfo.slotStatusType)
}

// -------------------------------------------------------------------

// SlotPoint

// optional int32 x = 1;
inline bool SlotPoint::_internal_has_x() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool SlotPoint::has_x() const {
  return _internal_has_x();
}
inline void SlotPoint::clear_x() {
  x_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline int32_t SlotPoint::_internal_x() const {
  return x_;
}
inline int32_t SlotPoint::x() const {
  // @@protoc_insertion_point(field_get:aph.SlotPoint.x)
  return _internal_x();
}
inline void SlotPoint::_internal_set_x(int32_t value) {
  _has_bits_[0] |= 0x00000001u;
  x_ = value;
}
inline void SlotPoint::set_x(int32_t value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:aph.SlotPoint.x)
}

// optional int32 y = 2;
inline bool SlotPoint::_internal_has_y() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool SlotPoint::has_y() const {
  return _internal_has_y();
}
inline void SlotPoint::clear_y() {
  y_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline int32_t SlotPoint::_internal_y() const {
  return y_;
}
inline int32_t SlotPoint::y() const {
  // @@protoc_insertion_point(field_get:aph.SlotPoint.y)
  return _internal_y();
}
inline void SlotPoint::_internal_set_y(int32_t value) {
  _has_bits_[0] |= 0x00000002u;
  y_ = value;
}
inline void SlotPoint::set_y(int32_t value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:aph.SlotPoint.y)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace aph

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::aph::ApaStatusType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::aph::ApaStatusType>() {
  return ::aph::ApaStatusType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_aph_2eproto
