// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aph.proto

#include "aph.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace aph {
constexpr apa_status::apa_status(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : m_current_apa_status_(0)
{}
struct apa_statusDefaultTypeInternal {
  constexpr apa_statusDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~apa_statusDefaultTypeInternal() {}
  union {
    apa_status _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT apa_statusDefaultTypeInternal _apa_status_default_instance_;
constexpr target_slot::target_slot(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : m_user_select_slot_label_idx_(0){}
struct target_slotDefaultTypeInternal {
  constexpr target_slotDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~target_slotDefaultTypeInternal() {}
  union {
    target_slot _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT target_slotDefaultTypeInternal _target_slot_default_instance_;
}  // namespace aph
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_aph_2eproto[2];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_aph_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_aph_2eproto = nullptr;

const uint32_t TableStruct_aph_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::aph::apa_status, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::aph::apa_status, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::aph::apa_status, m_current_apa_status_),
  0,
  PROTOBUF_FIELD_OFFSET(::aph::target_slot, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::aph::target_slot, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::aph::target_slot, m_user_select_slot_label_idx_),
  0,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, -1, sizeof(::aph::apa_status)},
  { 8, 15, -1, sizeof(::aph::target_slot)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::aph::_apa_status_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::aph::_target_slot_default_instance_),
};

const char descriptor_table_protodef_aph_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\taph.proto\022\003aph\"\\\n\napa_status\0225\n\024m_curr"
  "ent_apa_status\030\001 \001(\0162\022.aph.ApaStatusType"
  "H\000\210\001\001B\027\n\025_m_current_apa_status\"Y\n\013target"
  "_slot\022)\n\034m_user_select_slot_label_idx\030\001 "
  "\001(\005H\000\210\001\001B\037\n\035_m_user_select_slot_label_id"
  "x*\375\001\n\rApaStatusType\022\022\n\016APA_STATUS_OFF\020\000\022"
  "\026\n\022APA_STATUS_STANDBY\020\001\022\030\n\024APA_STATUS_SE"
  "ARCHING\020\002\022\030\n\024APA_STATUS_EXIT_PARK\020\003\022\025\n\021A"
  "PA_STATUS_ENABLE\020\004\022\027\n\023APA_STATUS_GUIDANC"
  "E\020\005\022\025\n\021APA_STATUS_FINISH\020\006\022\024\n\020APA_STATUS"
  "_ERROR\020\007\022\026\n\022APA_STATUS_PARKING\020\010\022\027\n\023APA_"
  "STATUS_RESERVED\020\tb\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_aph_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_aph_2eproto = {
  false, false, 465, descriptor_table_protodef_aph_2eproto, "aph.proto", 
  &descriptor_table_aph_2eproto_once, nullptr, 0, 2,
  schemas, file_default_instances, TableStruct_aph_2eproto::offsets,
  file_level_metadata_aph_2eproto, file_level_enum_descriptors_aph_2eproto, file_level_service_descriptors_aph_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_aph_2eproto_getter() {
  return &descriptor_table_aph_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_aph_2eproto(&descriptor_table_aph_2eproto);
namespace aph {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ApaStatusType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_aph_2eproto);
  return file_level_enum_descriptors_aph_2eproto[0];
}
bool ApaStatusType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class apa_status::_Internal {
 public:
  using HasBits = decltype(std::declval<apa_status>()._has_bits_);
  static void set_has_m_current_apa_status(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

apa_status::apa_status(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:aph.apa_status)
}
apa_status::apa_status(const apa_status& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  m_current_apa_status_ = from.m_current_apa_status_;
  // @@protoc_insertion_point(copy_constructor:aph.apa_status)
}

inline void apa_status::SharedCtor() {
m_current_apa_status_ = 0;
}

apa_status::~apa_status() {
  // @@protoc_insertion_point(destructor:aph.apa_status)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void apa_status::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void apa_status::ArenaDtor(void* object) {
  apa_status* _this = reinterpret_cast< apa_status* >(object);
  (void)_this;
}
void apa_status::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void apa_status::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void apa_status::Clear() {
// @@protoc_insertion_point(message_clear_start:aph.apa_status)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  m_current_apa_status_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* apa_status::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional .aph.ApaStatusType m_current_apa_status = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_m_current_apa_status(static_cast<::aph::ApaStatusType>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* apa_status::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:aph.apa_status)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional .aph.ApaStatusType m_current_apa_status = 1;
  if (_internal_has_m_current_apa_status()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_m_current_apa_status(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:aph.apa_status)
  return target;
}

size_t apa_status::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:aph.apa_status)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional .aph.ApaStatusType m_current_apa_status = 1;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_m_current_apa_status());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apa_status::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    apa_status::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*apa_status::GetClassData() const { return &_class_data_; }

void apa_status::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<apa_status *>(to)->MergeFrom(
      static_cast<const apa_status &>(from));
}


void apa_status::MergeFrom(const apa_status& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:aph.apa_status)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_m_current_apa_status()) {
    _internal_set_m_current_apa_status(from._internal_m_current_apa_status());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void apa_status::CopyFrom(const apa_status& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:aph.apa_status)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool apa_status::IsInitialized() const {
  return true;
}

void apa_status::InternalSwap(apa_status* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(m_current_apa_status_, other->m_current_apa_status_);
}

::PROTOBUF_NAMESPACE_ID::Metadata apa_status::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_aph_2eproto_getter, &descriptor_table_aph_2eproto_once,
      file_level_metadata_aph_2eproto[0]);
}

// ===================================================================

class target_slot::_Internal {
 public:
  using HasBits = decltype(std::declval<target_slot>()._has_bits_);
  static void set_has_m_user_select_slot_label_idx(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

target_slot::target_slot(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:aph.target_slot)
}
target_slot::target_slot(const target_slot& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  m_user_select_slot_label_idx_ = from.m_user_select_slot_label_idx_;
  // @@protoc_insertion_point(copy_constructor:aph.target_slot)
}

inline void target_slot::SharedCtor() {
m_user_select_slot_label_idx_ = 0;
}

target_slot::~target_slot() {
  // @@protoc_insertion_point(destructor:aph.target_slot)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void target_slot::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void target_slot::ArenaDtor(void* object) {
  target_slot* _this = reinterpret_cast< target_slot* >(object);
  (void)_this;
}
void target_slot::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void target_slot::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void target_slot::Clear() {
// @@protoc_insertion_point(message_clear_start:aph.target_slot)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  m_user_select_slot_label_idx_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* target_slot::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional int32 m_user_select_slot_label_idx = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_m_user_select_slot_label_idx(&has_bits);
          m_user_select_slot_label_idx_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* target_slot::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:aph.target_slot)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional int32 m_user_select_slot_label_idx = 1;
  if (_internal_has_m_user_select_slot_label_idx()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_m_user_select_slot_label_idx(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:aph.target_slot)
  return target;
}

size_t target_slot::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:aph.target_slot)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional int32 m_user_select_slot_label_idx = 1;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_m_user_select_slot_label_idx());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData target_slot::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    target_slot::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*target_slot::GetClassData() const { return &_class_data_; }

void target_slot::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<target_slot *>(to)->MergeFrom(
      static_cast<const target_slot &>(from));
}


void target_slot::MergeFrom(const target_slot& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:aph.target_slot)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_m_user_select_slot_label_idx()) {
    _internal_set_m_user_select_slot_label_idx(from._internal_m_user_select_slot_label_idx());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void target_slot::CopyFrom(const target_slot& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:aph.target_slot)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool target_slot::IsInitialized() const {
  return true;
}

void target_slot::InternalSwap(target_slot* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(m_user_select_slot_label_idx_, other->m_user_select_slot_label_idx_);
}

::PROTOBUF_NAMESPACE_ID::Metadata target_slot::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_aph_2eproto_getter, &descriptor_table_aph_2eproto_once,
      file_level_metadata_aph_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace aph
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::aph::apa_status* Arena::CreateMaybeMessage< ::aph::apa_status >(Arena* arena) {
  return Arena::CreateMessageInternal< ::aph::apa_status >(arena);
}
template<> PROTOBUF_NOINLINE ::aph::target_slot* Arena::CreateMaybeMessage< ::aph::target_slot >(Arena* arena) {
  return Arena::CreateMessageInternal< ::aph::target_slot >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
