// Generated by the boleidlc.  DO NOT EDIT!

#ifndef CAN_IDL_WRAPPER_H_
#define CAN_IDL_WRAPPER_H_
#ifndef GOOGLE_PROTOBUF_INCLUDED_can_2eproto
# include "can.pb.h"
#endif
#include "message/proto/proto_msg.hpp"
#include "message/proto/proto_serializer.hpp"


namespace can {
using VehicleCanDataMsg = hobot::message::ProtoMsg<VehicleCanData>;
using VehicleCanDataMsgSerializer = hobot::message::ProtobufSerializer<VehicleCanData>;

}  // namespace can


#endif

