// Generated by the boleidlc.  DO NOT EDIT!

#ifndef FSM_IDL_WRAPPER_H_
#define FSM_IDL_WRAPPER_H_
#ifndef GOOGLE_PROTOBUF_INCLUDED_fsm_2eproto
# include "fsm.pb.h"
#endif
#include "message/proto/proto_msg.hpp"
#include "message/proto/proto_serializer.hpp"


namespace fsm {
using SlotlabelMsg = hobot::message::ProtoMsg<Slotlabel>;
using SlotlabelMsgSerializer = hobot::message::ProtobufSerializer<Slotlabel>;

using ApastatusreqMsg = hobot::message::ProtoMsg<Apastatusreq>;
using ApastatusreqMsgSerializer = hobot::message::ProtobufSerializer<Apastatusreq>;

}  // namespace fsm


#endif

