// Generated by the boleidlc.  DO NOT EDIT!

#ifndef PSD_IDL_WRAPPER_H_
#define PSD_IDL_WRAPPER_H_
#ifndef GOOGLE_PROTOBUF_INCLUDED_psd_2eproto
# include "psd.pb.h"
#endif
#include "message/proto/proto_msg.hpp"
#include "message/proto/proto_serializer.hpp"


namespace psd {
using SApaPoint_IMsg = hobot::message::ProtoMsg<SApaPoint_I>;
using SApaPoint_IMsgSerializer = hobot::message::ProtobufSerializer<SApaPoint_I>;

using SApaPSRectMsg = hobot::message::ProtoMsg<SApaPSRect>;
using SApaPSRectMsgSerializer = hobot::message::ProtobufSerializer<SApaPSRect>;

using ImageMsg = hobot::message::ProtoMsg<Image>;
using ImageMsgSerializer = hobot::message::ProtobufSerializer<Image>;

using SApaPSInfoMsg = hobot::message::ProtoMsg<SApaPSInfo>;
using SApaPSInfoMsgSerializer = hobot::message::ProtobufSerializer<SApaPSInfo>;

}  // namespace psd


#endif

