// Generated by the boleidlc.  DO NOT EDIT!

#ifndef S32G_IDL_WRAPPER_H_
#define S32G_IDL_WRAPPER_H_
#ifndef GOOGLE_PROTOBUF_INCLUDED_s32g_2eproto
# include "s32g.pb.h"
#endif
#include "message/proto/proto_msg.hpp"
#include "message/proto/proto_serializer.hpp"


namespace s32g {
using slotlabelMsg = hobot::message::ProtoMsg<slotlabel>;
using slotlabelMsgSerializer = hobot::message::ProtobufSerializer<slotlabel>;

using apastatusreqMessageMsg = hobot::message::ProtoMsg<apastatusreqMessage>;
using apastatusreqMessageMsgSerializer = hobot::message::ProtobufSerializer<apastatusreqMessage>;

}  // namespace s32g


#endif

