// Generated by the boleidlc.  DO NOT EDIT!

#ifndef SEN_IDL_WRAPPER_H_
#define SEN_IDL_WRAPPER_H_
#ifndef GOOGLE_PROTOBUF_INCLUDED_sen_2eproto
# include "sen.pb.h"
#endif
#include "message/proto/proto_msg.hpp"
#include "message/proto/proto_serializer.hpp"


namespace sen {
using Point3DMsg = hobot::message::ProtoMsg<Point3D>;
using Point3DMsgSerializer = hobot::message::ProtobufSerializer<Point3D>;

using IMUDataMsg = hobot::message::ProtoMsg<IMUData>;
using IMUDataMsgSerializer = hobot::message::ProtobufSerializer<IMUData>;

using GNSSDataMsg = hobot::message::ProtoMsg<GNSSData>;
using GNSSDataMsgSerializer = hobot::message::ProtobufSerializer<GNSSData>;

using INSDataMsg = hobot::message::ProtoMsg<INSData>;
using INSDataMsgSerializer = hobot::message::ProtobufSerializer<INSData>;

using DualAntennaDataMsg = hobot::message::ProtoMsg<DualAntennaData>;
using DualAntennaDataMsgSerializer = hobot::message::ProtobufSerializer<DualAntennaData>;

}  // namespace sen


#endif

